version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "sqlalchemy"
        versions: ">=1.4.0"
      - dependency-name: "types-click"
        versions: ">=0.1.12"
    open-pull-requests-limit: 10
    assignees:
      - bryanforbes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - bryanforbes
