language: python
python:
  - "3.7"

dist: xenial
sudo: required

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - -y --preview
  - deactivate
  - source $HOME/.poetry/env
  - poetry config settings.virtualenvs.in-project true

install:
  - poetry install -v --extras "db gino_typed more_itertools uvloop"
  - poetry run pip install codecov

script: |
  set -e
  poetry run flake8 src
  poetry run mypy -m botus_receptus
  poetry run py.test -p no:sugar

after_success:
  - poetry run codecov
