language: python
python:
  - "3.7"

dist: xenial

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - pip install -U pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - -y
  - source $HOME/.poetry/env
  - poetry install -v --extras "db gino"

script:
  - poetry run py.test -p no:sugar
