language: python
python:
  - "3.7"

dist: xenial
sudo: required

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - -y --preview
  - source $HOME/.poetry/env

install:
  - poetry install -v --extras "db gino_typed"

script:
  - poetry run flake8 src/
  - poetry run py.test -p no:sugar
