language: python
python:
  - "3.7"

dist: xenial

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - pip install -U pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - -y --preview
  - source $HOME/.poetry/env
  - export XDG_CONFIG_HOME="$(pwd)/.config"
  - poetry config settings.virtualenvs.in-project true
  - poetry --version
  - poetry install -v --extras "db gino_typed"

script:
  - poetry run py.test -p no:sugar
