from typing import Any, overload
from os import PathLike
from pathlib import Path
from asyncio import AbstractEventLoop, Task

PY_36: bool
PY_37: bool
SYSTEM: str

def aiter_compat(func): ...
@overload
def fspath(path: str) -> str: ...
@overload
def fspath(path: bytes) -> bytes: ...
@overload
def fspath(path: PathLike) -> Any: ...
def get_pg_home_directory() -> Path: ...
def current_asyncio_task(loop: AbstractEventLoop) -> Task: ...
