import datetime
import decimal
import ipaddress
import uuid
from typing import Any

infinity_date: datetime.date
infinity_datetime: datetime.datetime
negative_infinity_date: datetime.date
negative_infinity_datetime: datetime.datetime
pg_epoch_date: datetime.date
pg_epoch_datetime: datetime.datetime
pg_epoch_datetime_utc: datetime.datetime
utc = datetime.timezone.utc
date_from_ordinal = datetime.date.fromordinal
_ipaddr = ipaddress.ip_address
_ipnet = ipaddress.ip_network

def __pyx_unpickle_CodecContext(*args, **kwargs) -> Any: ...

class CodecContext:
    __pyx_vtable__: Any = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def get_text_codec(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class ReadBuffer:
    __pyx_vtable__: Any = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class WriteBuffer:
    __pyx_vtable__: Any = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

_Dec = decimal.Decimal
_UUID = uuid.UUID
timedelta = datetime.timedelta
