name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: bryanforbes/python-workflows/.github/workflows/reusable-unit-tests.yml@master
    with:
      python_versions: '["3.11", "3.12"]'
      coverage: true
      poetry_args: '--extras all'
      pytest_args: '-p no:sugar'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
