name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - '3.11'
          - '3.12'
    uses: bryanforbes/python-workflows/.github/workflows/reusable-unit-tests-new.yml@master
    with:
      python_version: ${{ matrix.python-version }}
      coverage: true
      poetry_args: '--all-extras'
      pytest_args: '-p no:sugar'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
