name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/unit-tests.yml'
      - '.pre-commit-config.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - '3.12'
          - '3.13'
    uses: bryanforbes/python-workflows/.github/workflows/reusable-unit-tests-new.yml@master
    with:
      python_version: ${{ matrix.python-version }}
      coverage: true
      poetry_args: '--extras all'
      pytest_args: '-p no:sugar'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
